services:

  web-app:
    profiles: [container, webapp]
    build:
      context: ./webapp
      dockerfile: Dockerfile
    environment:
      - OLLAMA_BASE_URL=${OLLAMA_BASE_URL}
      - LLM=${LLM}
      - HTTP_PORT=${HTTP_PORT} 
      # host.docker.internal: listening the host from the container
    ports:
      - ${HTTP_PORT}:${HTTP_PORT}
    develop:
      watch:
        - action: sync
          path: ./webapp/public
          target: /app/public
        - action: rebuild
          path: ./webapp/index.mjs
          